spring:
  application:
    name: ms_cliente
  datasource:
    url: jdbc:mysql://localhost:3306/db_tienda_comics?createDatabaseIfNotExist=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
    validate-on-migrate: false

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /doc/swagger-ui/index.html
  api-docs:
    path: /api-docs
    enabled: true
    servers:
    - url: http://localhost:8081
      description: ms_cliente directo
    - url: http://localhost:8080/api/v1/clientes
      description: ms_cliente via Api Gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

